### ISSUE TITLE
Not working on Surface Laptop 3 15" (AMD Ryzen 5) 

### ISSUE THREAD

**Issue by iseries** [orev/dpst-control#2]
This is not working on my Surface Laptop 3 15" (AMD Ryzen 5) 

When execute the bat i get:
```
C:\Users\conta\Desktop\dpst-control-master\dpst-control.ps1 : Cannot locate FeatureTestControl in registry
In C:\Users\conta\Desktop\dpst-control-master\dpst-control.ps1:139 Zeichen:5
+     Write-Error "Cannot locate ${ftcName} in registry"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dpst-control.ps1
```

**Comment by orev** [comment]
DPST is "Intel® Display Power Saving Technology", so it is specific to Intel graphics chips. As such, it would not work on an AMD-based system.

There is info here on how to disable it for AMD systems, but I cannot test it as I don't have one:
    https://superuser.com/questions/639990/how-do-i-disable-vari-bright-atibtmon-exe-without-catalyst-control-center/644383

**Comment by iseries** [comment]
AMD != Intel ... sorry, that's so obviously. Sorry.
